site_name: CCBL Tutorials
nav:
    - Introduction to Linux: linux.md
    - Git: git.md
    - SSH: ssh.md
    - IDE: ide.md
    - Kill zombie processes: zombie.md
    - Slurm basics: hcp_aguia4.md
theme:
  name: 'material'

